{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ include "go-microservice-chart.fullname" . }}
    labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ .Release.Name }}
        release: {{ .Values.serviceMonitor.release | default "kube-prometheus-stack" | quote }}
spec:
    selector:
        matchLabels:
    {{- include "go-microservice-chart.selectorLabels" . | nindent 12 }}
    namespaceSelector:
        matchNames:
            - {{ .Release.Namespace }}
    endpoints:
        - port: {{ .Values.serviceMonitor.port | default "http" | quote }}
          path: {{ .Values.serviceMonitor.path | default "/metrics" }}
          interval: {{ .Values.serviceMonitor.interval | default "30s" }}
{{- end }}